### ISSUE TITLE
如果显示默认的第一个子菜单的内容该怎么写呢？

### ISSUE THREAD

**Issue by old-boy** [wangduanduan/vue-el-dashboard#1]
你好，你的方法很好用，把在 router 下一个个导入的路由给循环出来了，非常方便。
可是我现在有一个困惑，继续使用你的方法的情况下：

1.那如果我想显示 Sidebar 中第一个菜单呢，应该怎么写？
2.如果有其它的路由的情况下，又该怎么写呢？

默认情况下 router 是这样子的
export default new Router({
  routes: [
    {
      path: '/',
      name: 'sidebar',
      component: Sidebar
    }
  ]
})
对吧？
那你这个例子里直接将 router 返回为一个数组
var routes  = [];
export default new Router({ routes })

烦指点一下，谢谢！

**Comment by wangduanduan** [comment]
1.  不知道你有没有看过elementUI的官方文档，官方文档上有你第一个问题的答案，http://element-cn.eleme.io/#/zh-CN/component/menu， `default-active  当前激活菜单的 index`。
2. demo中的菜单使用的是两层的，如果想增加其他菜单，需要修改`config/menu-cconfig.js`

**Comment by wangduanduan** [comment]
建议多看看官方文档。
